### ISSUE TITLE
modal-body padding is covering up bottom half of close X

### ISSUE THREAD

**Issue by thinq4yourself** [WriteOn/WriteOnApp#42]
The `modal-header` contains the `<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>` tag to close the modal, but the `modal-body` has a padding that cuts off the bottom of the X and render it unavailable to click on. 

``` css
.modal .modal-body {
    padding: 20px;
}
```

needs to be changed to

``` css
.modal .modal-body {
    margin-top: 20px;
   padding: 0 20px 20px 20px;
}
```
